REDIS_CONFIG:
  # host: "containers-us-west-165.railway.app"  # redis 链接
  # port: 7952         # redis 端口
  # user: "default"                    # redis 用户名
  # auth: "m2nxBXmT4PmY0ClHkw1U"       # redis 连接密码
  db: "0"           # redis 数据库
  url: "redis://default:m2nxBXmT4PmY0ClHkw1U@containers-us-west-165.railway.app:5984"

MONGODB_CONFIG:
  name: "test_mongo"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://mongo:ifXR21tVHmD4xCH5MDa7@containers-us-west-135.railway.app:7190"   # 数据库链接地址
  # port: 7190
  # username: "mongo"                   # 数据库链接用户名
  # password: "ifXR21tVHmD4xCH5MDa7"                 # 数据库链接密码
  # database: "test"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能